fail_on_violations: true

rubocop:
  config_file: .rubocop.yml
  version: 0.59.2

scss:
  config_file: .scss-lint.yml

eslint:
  enabled: true
  version: 4.18.2
  config_file: .eslintrc

jshint:
  enabled: false
