# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: yarn install
- script: bundle exec rake db:create
- script: bundle exec rake schema:load
- script: bundle exec rake spec